trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
    displayName: 'Install Node.js 14.x'

- script: |
    npm install -g npm@6
    npm install -g copyfiles
    npm install --package-lock-only
    npm install
    npm run build:dev
  displayName: 'Install dependencies and build'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '/site/wwwroot'
    artifactName: 'drop'
  displayName: 'Publish build artifacts'

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
    checkLatest: true
  displayName: 'Use Node.js 14.x'

- script: |
    npm install -g serve
    serve -s out -l 8080
  displayName: 'Serve the application on port 8080'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(295b6628-0905-4b72-99cc-b89c3772f8b2)'
    appType: 'webAppLinux'
    appName: 'bundee-driverweb-DEV'
    package: '$(System.DefaultWorkingDirectory)/out'
    runtimeStack: 'NODE|14-lts'
    startUpCommand: 'serve -s -l 8080'
