FROM node:20.12.1

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Copy environment files into the container
COPY .env.qa .env.local

# Build the application
RUN npm run build:qa

EXPOSE 3000

CMD ["npm", "start"]
