version: '3.8'
services:
  client-qa:
    build:
      context: .
      dockerfile: Dockerfile.qa
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.qa
    